title: Hsin-Yu Hsieh # your name (or website title) here
logo: "/images/S__63799356.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst in Taiwan 
  Currently looking for job. 
  <br><br>
  <a href="https://www.linkedin.com/in/hsinyu-hsieh/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
